console.log(names.toUpperCase())
console.log(names.toLowerCase())
console.log(names.slice(1, 10))
console.log(names.split())
console.log(names.search("h"))
let b = "aaaa"
console.log(names.concat(" ",b,"jdv"))
console.log(names.replace("sai", "reddy"))
console.log(names.indexOf("rohan"))
console.log(names.charAt(11))